name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: Linux

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-bot
   
   
  deploy: 

     runs-on: Linux
     needs: [build]
     steps:
     - uses: actions/checkout@v3
     - name: run the Docker image
       run: docker run -d --rm --restart=always--name=telegabot my-bot
